import type { CheckboxConfig, CheckboxGroupConfig, ComboBoxConfig, DialogConfig, DrawerConfig, NumberFieldConfig, PopoverConfig, RadioConfig, RadioGroupConfig, SearchFieldConfig, SelectFieldConfig, SliderConfig, SwitchConfig, TextAreaConfig, TextFieldConfig, ThemeConfig } from "./types";

export const defaultTheme: ThemeConfig = {
  tokens: {
    colors: {
      // Burnt amber-orange — the last warm glow on the horizon
      primary: {
        50:  "#fef8ee",
        100: "#fdefd4",
        200: "#fad9a4",
        300: "#f7bc68",
        400: "#f39828",
        500: "#e8780f",
        600: "#cb5e09",
        700: "#a3450a",
        800: "#83360e",
        900: "#6b2d0f",
        950: "#3a1505",
      },
      // Cool slate-blue — the upper sky after the sun has dropped
      neutral: {
        50:  "#f2f4f7",
        100: "#e3e8ef",
        200: "#c4cedb",
        300: "#9aafc4",
        400: "#6a8ea8",
        500: "#4a7090",
        600: "#385873",
        700: "#294358",
        800: "#1b2e3e",
        900: "#101d28",
        950: "#070e16",
      },
      // Muted rose — restrained, not alarming
      danger: {
        50:  "#fff1f2",
        100: "#ffe0e2",
        200: "#ffc6ca",
        300: "#ff99a0",
        400: "#ff5d67",
        500: "#f83040",
        600: "#e01128",
        700: "#bc0d22",
        800: "#9b0f21",
        900: "#811323",
        950: "#47040e",
      },
      // Muted teal — calm, natural, not too green
      success: {
        50:  "#effaf6",
        100: "#d9f3e8",
        200: "#b4e6d3",
        300: "#81d2b8",
        400: "#4ab899",
        500: "#289c7f",
        600: "#1a7d67",
        700: "#176453",
        800: "#165043",
        900: "#144238",
        950: "#09251f",
      },
      // Deep amber — warning that reads as considered, not panicked
      warning: {
        50:  "#fffbeb",
        100: "#fef3c7",
        200: "#fde68a",
        300: "#fbd152",
        400: "#f8b922",
        500: "#e99a09",
        600: "#cc7504",
        700: "#a35408",
        800: "#87410e",
        900: "#71360f",
        950: "#401b04",
      },
    },
    radii: {
      none: "rounded-none",
      sm:   "rounded-sm",
      md:   "rounded-md",
      lg:   "rounded-lg",
      xl:   "rounded-xl",
      full: "rounded-full",
    },
    shadows: {
      none: "shadow-none",
      sm:   "shadow-sm",
      md:   "shadow-md",
      lg:   "shadow-lg",
      xl:   "shadow-xl",
    },
    animation: {
      duration: {
        fast:   "100ms",
        normal: "150ms",
        slow:   "300ms",
      },
      easing: {
        default: "ease-out",
        spring:  "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },

  components: {
    button: {
      base:       "inline-flex items-center justify-center font-medium transition-colors focus-visible:outline-none",
      ripple:     true,
      pressScale: true,

      size: {
        xs: {
          height:        "h-6",
          paddingX:      "px-2",
          fontSize:      "text-xs",
          fontWeight:    "font-medium",
          letterSpacing: "tracking-normal",
          borderRadius:  "rounded",
          gap:           "gap-1",
          iconSize:      "size-3",
          spinnerSize:   "size-3",
        },
        sm: {
          height:        "h-8",
          paddingX:      "px-3",
          fontSize:      "text-sm",
          fontWeight:    "font-medium",
          letterSpacing: "tracking-normal",
          borderRadius:  "rounded",
          gap:           "gap-1.5",
          iconSize:      "size-3.5",
          spinnerSize:   "size-3.5",
        },
        md: {
          height:        "h-10",
          paddingX:      "px-4",
          fontSize:      "text-base",
          fontWeight:    "font-medium",
          letterSpacing: "tracking-normal",
          borderRadius:  "rounded-md",
          gap:           "gap-2",
          iconSize:      "size-4",
          spinnerSize:   "size-4",
        },
        lg: {
          height:        "h-12",
          paddingX:      "px-5",
          fontSize:      "text-lg",
          fontWeight:    "font-medium",
          letterSpacing: "tracking-normal",
          borderRadius:  "rounded-md",
          gap:           "gap-2",
          iconSize:      "size-5",
          spinnerSize:   "size-5",
        },
        xl: {
          height:        "h-14",
          paddingX:      "px-6",
          fontSize:      "text-xl",
          fontWeight:    "font-semibold",
          letterSpacing: "tracking-wide",
          borderRadius:  "rounded-lg",
          gap:           "gap-2.5",
          iconSize:      "size-5",
          spinnerSize:   "size-5",
        },
      },

      intent: {
        primary: {
          default:      { bg: "bg-orange-700",            text: "text-white",        border: "border-transparent", shadow: "shadow-sm" },
          hover:        { bg: "hover:bg-orange-800",       text: "text-white",        border: "border-transparent", shadow: "hover:shadow-md" },
          pressed:      { bg: "active:bg-orange-900",      scale: "active:scale-95" },
          focusVisible: "focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-orange-600",
          disabled:     { bg: "bg-orange-300",            text: "text-white/70",     opacity: "opacity-60",        cursor: "cursor-not-allowed" },
          loading:      { bg: "bg-orange-700",            spinnerColor: "text-white/80" },
        },
        secondary: {
          default:      { bg: "bg-slate-100",             text: "text-slate-800",    border: "border-transparent", shadow: "shadow-none" },
          hover:        { bg: "hover:bg-slate-200",        text: "text-slate-900",    border: "border-transparent", shadow: "shadow-none" },
          pressed:      { bg: "active:bg-slate-300",       scale: "active:scale-95" },
          focusVisible: "focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-slate-400",
          disabled:     { bg: "bg-slate-100",             text: "text-slate-400",    opacity: "opacity-60",        cursor: "cursor-not-allowed" },
          loading:      { bg: "bg-slate-100",             spinnerColor: "text-slate-500" },
        },
        ghost: {
          default:      { bg: "bg-transparent",           text: "text-slate-600",    border: "border-transparent", shadow: "shadow-none" },
          hover:        { bg: "hover:bg-slate-100",        text: "text-slate-800",    border: "border-transparent", shadow: "shadow-none" },
          pressed:      { bg: "active:bg-slate-200",       scale: "active:scale-95" },
          focusVisible: "focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-slate-400",
          disabled:     { bg: "bg-transparent",           text: "text-slate-400",    opacity: "opacity-50",        cursor: "cursor-not-allowed" },
          loading:      { bg: "bg-transparent",           spinnerColor: "text-slate-500" },
        },
        outline: {
          default:      { bg: "bg-transparent",           text: "text-orange-700",   border: "border-2 border-orange-700", shadow: "shadow-none" },
          hover:        { bg: "hover:bg-orange-700",       text: "hover:text-white",  border: "border-transparent",         shadow: "shadow-none" },
          pressed:      { bg: "active:bg-orange-800",      scale: "active:scale-95" },
          focusVisible: "focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-orange-600",
          disabled:     { bg: "bg-transparent",           text: "text-orange-300",   opacity: "opacity-60",                cursor: "cursor-not-allowed" },
          loading:      { bg: "bg-transparent",           spinnerColor: "text-orange-600" },
        },
        danger: {
          default:      { bg: "bg-rose-700",              text: "text-white",        border: "border-transparent", shadow: "shadow-sm" },
          hover:        { bg: "hover:bg-rose-800",         text: "text-white",        border: "border-transparent", shadow: "hover:shadow-md" },
          pressed:      { bg: "active:bg-rose-900",        scale: "active:scale-95" },
          focusVisible: "focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-rose-600",
          disabled:     { bg: "bg-rose-300",              text: "text-white/70",     opacity: "opacity-60",        cursor: "cursor-not-allowed" },
          loading:      { bg: "bg-rose-700",              spinnerColor: "text-white/80" },
        },
        link: {
          default:      { bg: "bg-transparent",           text: "text-orange-700",   border: "border-transparent", shadow: "shadow-none" },
          hover:        { bg: "hover:bg-transparent",      text: "hover:text-orange-900 underline", border: "border-transparent", shadow: "shadow-none" },
          pressed:      { bg: "active:bg-transparent",     scale: "" },
          focusVisible: "focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-orange-600",
          disabled:     { bg: "bg-transparent",           text: "text-orange-300",   opacity: "opacity-60",        cursor: "cursor-not-allowed" },
          loading:      { bg: "bg-transparent",           spinnerColor: "text-orange-600" },
        },
      },

      shape: {
        rounded: { borderRadius: "rounded-md",   paddingX: "",     aspectRatio: "" },
        pill:    { borderRadius: "rounded-full",  paddingX: "px-5", aspectRatio: "" },
        square:  { borderRadius: "rounded-md",   paddingX: "p-0",  aspectRatio: "aspect-square" },
      },
    },

    checkbox: {
      root: "group inline-flex items-center cursor-pointer data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50",
      box: "shrink-0 flex items-center justify-center rounded border transition-colors",
      boxUnchecked: "border-neutral-300 bg-white",
      boxChecked: "border-orange-500 bg-orange-500",
      boxIndeterminate: "border-orange-500 bg-orange-500",
      boxDisabled: "",
      boxInvalid: "border-red-500",
      boxFocusVisible: "outline-none ring-2 ring-orange-500/40 ring-offset-1",
      icon: "text-white",
      label: "text-neutral-900 select-none",
      description: "text-neutral-500",
      size: {
        sm: { box: "h-3.5 w-3.5", fontSize: "text-xs",   gap: "gap-1.5", iconSize: "h-2.5 w-2.5" },
        md: { box: "h-4 w-4",     fontSize: "text-sm",   gap: "gap-2",   iconSize: "h-3 w-3" },
        lg: { box: "h-5 w-5",     fontSize: "text-base", gap: "gap-2.5", iconSize: "h-3.5 w-3.5" },
      },
    },

    checkboxGroup: {
      root:              "flex flex-col gap-1.5",
      label:             "text-sm font-medium text-neutral-700",
      requiredIndicator: "ml-0.5 text-red-500",
      description:       "text-xs text-neutral-500",
      error:             "text-xs text-red-600",
      items:             "flex flex-col gap-2",
    },

    popover: {
      container: "rounded-lg border border-neutral-200 bg-white shadow-lg outline-none",
      arrow: "fill-white stroke-neutral-200",
      offset: 8,
    },

    radio: {
      root: "group inline-flex items-center cursor-pointer data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50",
      indicator: "shrink-0 flex items-center justify-center rounded-full border transition-colors",
      indicatorUnselected: "border-neutral-300 bg-white",
      indicatorSelected: "border-orange-500 bg-orange-500",
      indicatorDisabled: "",
      indicatorInvalid: "border-red-500",
      indicatorFocusVisible: "outline-none ring-2 ring-orange-500/40 ring-offset-1",
      dot: "rounded-full bg-white",
      label: "text-neutral-900 select-none",
      description: "text-neutral-500",
      size: {
        sm: { indicator: "h-3.5 w-3.5", dot: "h-1.5 w-1.5", fontSize: "text-xs",   gap: "gap-1.5" },
        md: { indicator: "h-4 w-4",     dot: "h-2 w-2",     fontSize: "text-sm",   gap: "gap-2"   },
        lg: { indicator: "h-5 w-5",     dot: "h-2.5 w-2.5", fontSize: "text-base", gap: "gap-2.5" },
      },
    },

    radioGroup: {
      root:              "flex flex-col gap-1.5",
      label:             "text-sm font-medium text-neutral-700",
      requiredIndicator: "ml-0.5 text-red-500",
      description:       "text-xs text-neutral-500",
      error:             "text-xs text-red-600",
      items:             "flex flex-col gap-2",
      itemsHorizontal:   "flex flex-row flex-wrap gap-x-4 gap-y-2",
    },

    slider: {
      root: "flex flex-col gap-2 w-full",
      label: "text-sm font-medium text-neutral-700",
      output: "text-sm tabular-nums text-neutral-500",
      track: "relative w-full rounded-full cursor-pointer",
      trackUnfilled: "bg-neutral-200",
      trackFilled: "rounded-full bg-orange-500",
      thumb: "absolute top-1/2 -translate-y-1/2 rounded-full bg-white border-2 border-orange-500 shadow transition-colors cursor-grab active:cursor-grabbing",
      thumbFocusVisible: "outline-none ring-2 ring-orange-500/40 ring-offset-1",
      thumbDragging: "cursor-grabbing",
      description: "text-xs text-neutral-500",
      error: "text-xs text-red-600",
      size: {
        sm: { trackHeight: "h-1",   thumb: "h-3.5 w-3.5", fontSize: "text-xs" },
        md: { trackHeight: "h-1.5", thumb: "h-4 w-4",     fontSize: "text-sm" },
      },
    },

    switch: {
      root: "group inline-flex items-center cursor-pointer data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50",
      track: "shrink-0 inline-flex items-center rounded-full p-0.5 transition-colors",
      trackOff: "bg-neutral-300",
      trackOn: "bg-orange-500",
      trackDisabled: "",
      trackFocusVisible: "outline-none ring-2 ring-orange-500/40 ring-offset-1",
      thumb: "rounded-full bg-white shadow transition-transform",
      label: "text-neutral-900 select-none",
      size: {
        sm: { track: "w-7 h-4",  thumb: "h-3 w-3", thumbTranslate: "translateX(12px)", fontSize: "text-xs",  gap: "gap-1.5" },
        md: { track: "w-9 h-5",  thumb: "h-4 w-4", thumbTranslate: "translateX(16px)", fontSize: "text-sm",  gap: "gap-2"   },
      },
    },

    comboBox: {
      root:              "group flex flex-col gap-1.5",
      label:             "text-sm font-medium text-neutral-700 group-data-[disabled]:opacity-50",
      requiredIndicator: "ml-0.5 text-red-500",
      description:       "text-xs text-neutral-500",
      error:             "text-xs text-red-600",
      inputWrapper: [
        "relative flex items-center overflow-hidden rounded-md border border-neutral-300 bg-white",
        "transition-[border-color,box-shadow]",
        "group-data-[focused]:border-orange-500 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-500/20",
        "group-data-[open]:border-orange-500 group-data-[open]:ring-2 group-data-[open]:ring-orange-500/20",
        "group-data-[invalid]:border-red-500",
        "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
        "group-data-[invalid]:group-data-[open]:ring-red-500/20",
        "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:bg-neutral-50 group-data-[disabled]:opacity-50",
      ].join(" "),
      input:    "flex-1 h-full bg-transparent text-neutral-900 outline-none placeholder:text-neutral-400 group-data-[disabled]:cursor-not-allowed",
      button: [
        "shrink-0 flex items-center justify-center text-neutral-400",
        "outline-none data-[focus-visible]:outline-none",
        "hover:text-neutral-600",
        "transition-transform duration-200 group-data-[open]:rotate-180",
      ].join(" "),
      adornment:     "absolute flex items-center justify-center text-neutral-400 pointer-events-none select-none",
      popover: [
        "min-w-[var(--trigger-width)] rounded-md border border-neutral-200 bg-white shadow-lg outline-none z-50",
        "mr-sf-popover",
      ].join(" "),
      listBox:       "p-1 max-h-64 overflow-y-auto overflow-x-hidden outline-none",
      item:          "flex items-center gap-2 px-2 py-1.5 rounded-sm text-sm text-neutral-900 cursor-default outline-none select-none transition-colors",
      itemFocused:   "bg-orange-50 text-orange-900",
      itemSelected:  "font-medium",
      itemDisabled:  "opacity-40 cursor-not-allowed",
      sectionHeader: "px-2 py-1 mt-1 text-xs font-semibold text-neutral-400 uppercase tracking-wide select-none",
      separator:     "my-1 border-t border-neutral-100",
      size: {
        sm: { height: "h-8",  fontSize: "text-sm",   paddingLeft: "pl-2.5", withPrefix: "pl-8",  paddingRight: "pr-8",  adornmentWidth: "w-8",  buttonWidth: "w-8"  },
        md: { height: "h-10", fontSize: "text-sm",   paddingLeft: "pl-3",   withPrefix: "pl-9",  paddingRight: "pr-9",  adornmentWidth: "w-9",  buttonWidth: "w-9"  },
        lg: { height: "h-11", fontSize: "text-base", paddingLeft: "pl-3.5", withPrefix: "pl-10", paddingRight: "pr-10", adornmentWidth: "w-10", buttonWidth: "w-10" },
      },
      glow: {
        type:     "static",
        color:    "rgba(249, 115, 22, 0.35)",
        blur:     10,
        spread:   4,
        radius:   10,
        opacity:  1,
        duration: 250,
      },
      gradientBorder: {
        stops:        ["#f97316", "#ec4899", "#8b5cf6"],
        invalidStops: ["#ef4444", "#f97316", "#ef4444"],
        width:        2,
        radius:       6,
        duration:     4,
        opacity:      0.9,
        fadeIn:       200,
      },
      svgStroke: {
        color:         "#f97316",
        invalidColor:  "#ef4444",
        width:         1.5,
        rx:            6,
        duration:      400,
        easing:        "ease-out",
        drawDirection: "clockwise",
      },
      inkDraw: {
        color:        "#f97316",
        invalidColor: "#ef4444",
        strokeWidth:  1.5,
        wobble:       2,
        rx:           6,
        duration:     350,
        easing:       "cubic-bezier(0.2, 0, 0, 1)",
      },
      corners: {
        style:        "corners",
        color:        "#f97316",
        invalidColor: "#ef4444",
        width:        2,
        length:       10,
        offset:       6,
        inset:        4,
        duration:     300,
        easing:       "ease-out",
      },
      cursorSpotlight: {
        color:   "rgba(249, 115, 22, 0.12)",
        radius:  80,
        fadeOut: 300,
      },
      bgReveal: {
        color:     "rgba(249, 115, 22, 0.07)",
        direction: "left",
        duration:  300,
        easing:    "ease-out",
      },
      ripple: {
        variant:  "ripple",
        color:    "rgba(249, 115, 22, 0.20)",
        duration: 600,
        radius:   6,
      },
      morphRadius: {
        rest:     "6px",
        focus:    "14px",
        duration: 250,
        easing:   "ease-out",
      },
      chromaBorder: {
        variant: "hue-rotate",
        opacity: 0.9,
        width:   2,
        radius:  6,
      },
    },

    selectField: {
      root:              "group flex flex-col gap-1.5",
      label:             "text-sm font-medium text-neutral-700 group-data-[disabled]:opacity-50",
      requiredIndicator: "ml-0.5 text-red-500",
      description:       "text-xs text-neutral-500",
      error:             "text-xs text-red-600",
      trigger: [
        "relative flex items-center w-full overflow-hidden rounded-md border border-neutral-300 bg-white cursor-pointer",
        "outline-none data-[focus-visible]:outline-none",
        "transition-[border-color,box-shadow]",
        "group-data-[focused]:border-orange-500 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-500/20",
        "group-data-[open]:border-orange-500 group-data-[open]:ring-2 group-data-[open]:ring-orange-500/20",
        "group-data-[invalid]:border-red-500",
        "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
        "group-data-[invalid]:group-data-[open]:ring-red-500/20",
        "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:bg-neutral-50 group-data-[disabled]:opacity-50",
      ].join(" "),
      valueText:   "text-neutral-900",
      placeholder: "text-neutral-400",
      chevron: [
        "shrink-0 flex items-center justify-center text-neutral-400 pointer-events-none",
        "transition-transform duration-200 group-data-[open]:rotate-180",
      ].join(" "),
      popover: [
        "min-w-[var(--trigger-width)] rounded-md border border-neutral-200 bg-white shadow-lg outline-none z-50",
        "mr-sf-popover",
      ].join(" "),
      listBox:       "p-1 max-h-64 overflow-y-auto overflow-x-hidden outline-none",
      item:          "flex items-center gap-2 px-2 py-1.5 rounded-sm text-sm text-neutral-900 cursor-default outline-none select-none transition-colors",
      itemFocused:   "bg-orange-50 text-orange-900",
      itemSelected:  "font-medium",
      itemDisabled:  "opacity-40 cursor-not-allowed",
      sectionHeader: "px-2 py-1 mt-1 text-xs font-semibold text-neutral-400 uppercase tracking-wide select-none",
      separator:     "my-1 border-t border-neutral-100",
      size: {
        sm: { height: "h-8",  fontSize: "text-sm",   paddingLeft: "pl-2.5", chevronWidth: "w-8"  },
        md: { height: "h-10", fontSize: "text-sm",   paddingLeft: "pl-3",   chevronWidth: "w-9"  },
        lg: { height: "h-11", fontSize: "text-base", paddingLeft: "pl-3.5", chevronWidth: "w-10" },
      },
      glow: {
        type:     "static",
        color:    "rgba(249, 115, 22, 0.35)",
        blur:     10,
        spread:   4,
        radius:   10,
        opacity:  1,
        duration: 250,
      },
      gradientBorder: {
        stops:        ["#f97316", "#ec4899", "#8b5cf6"],
        invalidStops: ["#ef4444", "#f97316", "#ef4444"],
        width:        2,
        radius:       6,
        duration:     4,
        opacity:      0.9,
        fadeIn:       200,
      },
      svgStroke: {
        color:         "#f97316",
        invalidColor:  "#ef4444",
        width:         1.5,
        rx:            6,
        duration:      400,
        easing:        "ease-out",
        drawDirection: "clockwise",
      },
      inkDraw: {
        color:        "#f97316",
        invalidColor: "#ef4444",
        strokeWidth:  1.5,
        wobble:       2,
        rx:           6,
        duration:     350,
        easing:       "cubic-bezier(0.2, 0, 0, 1)",
      },
      corners: {
        style:        "corners",
        color:        "#f97316",
        invalidColor: "#ef4444",
        width:        2,
        length:       10,
        offset:       6,
        inset:        4,
        duration:     300,
        easing:       "ease-out",
      },
      cursorSpotlight: {
        color:   "rgba(249, 115, 22, 0.12)",
        radius:  80,
        fadeOut: 300,
      },
      bgReveal: {
        color:     "rgba(249, 115, 22, 0.07)",
        direction: "left",
        duration:  300,
        easing:    "ease-out",
      },
      ripple: {
        variant:  "ripple",
        color:    "rgba(249, 115, 22, 0.20)",
        duration: 600,
        radius:   6,
      },
      morphRadius: {
        rest:     "6px",
        focus:    "14px",
        duration: 250,
        easing:   "ease-out",
      },
      chromaBorder: {
        variant: "hue-rotate",
        opacity: 0.9,
        width:   2,
        radius:  6,
      },
    },

    searchField: {
      root:              "group flex flex-col gap-1.5",
      label:             "text-sm font-medium text-neutral-700 group-data-[disabled]:opacity-50",
      requiredIndicator: "ml-0.5 text-red-500",
      description:       "text-xs text-neutral-500",
      error:             "text-xs text-red-600",
      inputWrapper: [
        "relative flex items-center overflow-hidden rounded-md border border-neutral-300 bg-white",
        "transition-[border-color,box-shadow]",
        "group-data-[focused]:border-orange-500 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-500/20",
        "group-data-[invalid]:border-red-500",
        "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
        "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:bg-neutral-50 group-data-[disabled]:opacity-50",
      ].join(" "),
      input:       "flex-1 h-full bg-transparent text-neutral-900 outline-none placeholder:text-neutral-400 group-data-[disabled]:cursor-not-allowed",
      adornment:   "absolute flex items-center justify-center text-neutral-400 pointer-events-none select-none",
      clearButton: "absolute flex items-center justify-center text-neutral-400 transition-colors hover:text-neutral-700 focus:outline-none",
      size: {
        sm: {
          height:         "h-8",
          fontSize:       "text-sm",
          paddingLeft:    "pl-2.5",
          paddingRight:   "pr-2.5",
          withPrefix:     "pl-8",
          withSuffix:     "pr-8",
          adornmentWidth: "w-8",
        },
        md: {
          height:         "h-10",
          fontSize:       "text-sm",
          paddingLeft:    "pl-3",
          paddingRight:   "pr-3",
          withPrefix:     "pl-9",
          withSuffix:     "pr-9",
          adornmentWidth: "w-9",
        },
        lg: {
          height:         "h-11",
          fontSize:       "text-base",
          paddingLeft:    "pl-3.5",
          paddingRight:   "pr-3.5",
          withPrefix:     "pl-10",
          withSuffix:     "pr-10",
          adornmentWidth: "w-10",
        },
      },
      glow: {
        type:     "static",
        color:    "rgba(249, 115, 22, 0.35)",
        blur:     10,
        spread:   4,
        radius:   10,
        opacity:  1,
        duration: 250,
      },
      gradientBorder: {
        stops:        ["#f97316", "#ec4899", "#8b5cf6"],
        invalidStops: ["#ef4444", "#f97316", "#ef4444"],
        width:        2,
        radius:       6,
        duration:     4,
        opacity:      0.9,
        fadeIn:       200,
      },
      svgStroke: {
        color:         "#f97316",
        invalidColor:  "#ef4444",
        width:         1.5,
        rx:            6,
        duration:      400,
        easing:        "ease-out",
        drawDirection: "clockwise",
      },
      inkDraw: {
        color:        "#f97316",
        invalidColor: "#ef4444",
        strokeWidth:  1.5,
        wobble:       2,
        rx:           6,
        duration:     350,
        easing:       "cubic-bezier(0.2, 0, 0, 1)",
      },
      corners: {
        style:        "corners",
        color:        "#f97316",
        invalidColor: "#ef4444",
        width:        2,
        length:       10,
        offset:       6,
        inset:        4,
        duration:     300,
        easing:       "ease-out",
      },
      characterReveal: {
        variant:    "char-fade",
        caretColor: "#374151",
        duration:   120,
        easing:     "ease-out",
      },
      cursorSpotlight: {
        color:   "rgba(249, 115, 22, 0.12)",
        radius:  80,
        fadeOut: 300,
      },
      bgReveal: {
        color:     "rgba(249, 115, 22, 0.07)",
        direction: "left",
        duration:  300,
        easing:    "ease-out",
      },
      ripple: {
        variant:  "ripple",
        color:    "rgba(249, 115, 22, 0.20)",
        duration: 600,
        radius:   6,
      },
      morphRadius: {
        rest:     "6px",
        focus:    "14px",
        duration: 250,
        easing:   "ease-out",
      },
      chromaBorder: {
        variant: "hue-rotate",
        opacity: 0.9,
        width:   2,
        radius:  6,
      },
    },

    drawer: {
      overlay:    "fixed inset-0 z-50 bg-black/40",
      panel:      "z-50 bg-white shadow-2xl outline-none flex flex-col",
      horizontal: {
        sm:   "w-64",
        md:   "w-80",
        lg:   "w-96",
        full: "w-screen",
      },
      vertical: {
        sm:   "h-48",
        md:   "h-64",
        lg:   "h-96",
        full: "h-dvh",
      },
      header:      "flex items-center justify-between px-6 py-4 border-b border-neutral-100 shrink-0",
      title:       "text-base font-semibold text-neutral-900",
      closeButton: "rounded-md p-1 text-neutral-400 hover:text-neutral-600 hover:bg-neutral-100 transition-colors outline-none focus-visible:ring-2 focus-visible:ring-orange-500/40",
      body:        "flex-1 overflow-y-auto px-6 py-4 min-h-0",
      footer:      "flex items-center justify-end gap-3 px-6 py-4 border-t border-neutral-100 shrink-0",
    },

    dialog: {
      overlay: "fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4",
      panel: "bg-white shadow-2xl outline-none flex flex-col w-full",
      size: {
        sm:   "max-w-sm   max-h-[85vh] rounded-xl",
        md:   "max-w-lg   max-h-[85vh] rounded-xl",
        lg:   "max-w-2xl  max-h-[90vh] rounded-xl",
        full: "max-w-none max-h-none   rounded-none w-screen h-dvh",
      },
      header:      "flex items-center justify-between px-6 py-4 border-b border-neutral-100 shrink-0",
      title:       "text-base font-semibold text-neutral-900",
      closeButton: "rounded-md p-1 text-neutral-400 hover:text-neutral-600 hover:bg-neutral-100 transition-colors outline-none focus-visible:ring-2 focus-visible:ring-orange-500/40",
      body:        "flex-1 overflow-y-auto px-6 py-4 min-h-0",
      footer:      "flex items-center justify-end gap-3 px-6 py-4 border-t border-neutral-100 shrink-0",
    },

    numberField: {
      root:              "group flex flex-col gap-1.5",
      label:             "text-sm font-medium text-neutral-700 group-data-[disabled]:opacity-50",
      requiredIndicator: "ml-0.5 text-red-500",
      description:       "text-xs text-neutral-500",
      error:             "text-xs text-red-600",
      group: [
        "relative flex w-full overflow-hidden rounded-md border border-neutral-300 bg-white",
        "transition-[border-color,box-shadow]",
        "group-data-[focused]:border-orange-500 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-500/20",
        "group-data-[invalid]:border-red-500",
        "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
        "group-data-[disabled]:bg-neutral-50 group-data-[disabled]:cursor-not-allowed",
      ].join(" "),
      input: [
        "flex-1 min-w-0 h-full bg-transparent text-neutral-900 placeholder:text-neutral-400 tabular-nums",
        "focus:outline-none",
        "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:opacity-50",
      ].join(" "),
      stepperColumn: "flex flex-col shrink-0 border-l border-neutral-300",
      stepperSeparator: "border-t border-neutral-300",
      stepperButton: [
        "flex flex-1 items-center justify-center text-neutral-400",
        "hover:bg-neutral-50 hover:text-neutral-600",
        "data-[pressed]:bg-neutral-100",
        "data-[disabled]:opacity-40 data-[disabled]:cursor-not-allowed data-[disabled]:hover:bg-transparent",
        "data-[focus-visible]:outline-none data-[focus-visible]:ring-2 data-[focus-visible]:ring-inset data-[focus-visible]:ring-orange-500/50",
        "transition-colors",
      ].join(" "),
      size: {
        sm: { height: "h-8",  fontSize: "text-sm",   paddingLeft: "pl-2.5", stepperWidth: "w-7" },
        md: { height: "h-9",  fontSize: "text-sm",   paddingLeft: "pl-3",   stepperWidth: "w-8" },
        lg: { height: "h-10", fontSize: "text-base", paddingLeft: "pl-3.5", stepperWidth: "w-9" },
      },
      glow: {
        type:    "static",
        color:   "rgba(249, 115, 22, 0.35)",
        blur:    8,
        spread:  5,
        radius:  10,
        opacity: 1,
      },
      gradientBorder: {
        stops:   ["#f97316", "#ec4899", "#a855f7", "#3b82f6"],
        width:   2,
        radius:  6,
        opacity: 0.9,
      },
      svgStroke: {
        color:        "#f97316",
        invalidColor: "#ef4444",
        width:        1.5,
        rx:           6,
        duration:     400,
        easing:       "ease-out",
      },
      corners: {
        style:        "corners",
        color:        "#f97316",
        invalidColor: "#ef4444",
        width:        2,
        length:       10,
        offset:       6,
        inset:        4,
        duration:     300,
        easing:       "ease-out",
      },
      bgReveal: {
        color:     "rgba(249, 115, 22, 0.07)",
        direction: "left",
        duration:  300,
        easing:    "ease-out",
      },
      ripple: {
        variant:  "pulse-rings",
        color:    "rgba(249, 115, 22, 0.35)",
        duration: 1500,
        radius:   6,
      },
      cursorSpotlight: {
        color:   "rgba(249, 115, 22, 0.10)",
        radius:  80,
        fadeOut: 300,
      },
      inkDraw: {
        color:        "#f97316",
        invalidColor: "#ef4444",
        strokeWidth:  1.5,
        wobble:       2,
        rx:           6,
        duration:     350,
        easing:       "cubic-bezier(0.2, 0, 0, 1)",
      },
      morphRadius: {
        rest:     "0.375rem",
        focus:    "0.75rem",
        duration: 250,
        easing:   "ease-out",
      },
      chromaBorder: {
        variant: "hue-rotate",
        opacity: 0.9,
        width:   2,
        radius:  6,
      },
    },

    textField: {
      root:              "group flex flex-col gap-1.5",
      label:             "text-sm font-medium text-neutral-700 group-data-[disabled]:opacity-50",
      requiredIndicator: "ml-0.5 text-red-500",
      description:       "text-xs text-neutral-500",
      error:             "text-xs text-red-600",
      inputWrapper: [
        "relative flex items-center overflow-hidden rounded-md border border-neutral-300 bg-white",
        "transition-[border-color,box-shadow]",
        "group-data-[focused]:border-orange-500 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-500/20",
        "group-data-[invalid]:border-red-500",
        "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
        "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:bg-neutral-50 group-data-[disabled]:opacity-50",
      ].join(" "),
      input:       "flex-1 h-full bg-transparent text-neutral-900 outline-none placeholder:text-neutral-400 group-data-[disabled]:cursor-not-allowed",
      adornment:   "absolute flex items-center justify-center text-neutral-400 pointer-events-none select-none",
      clearButton: "absolute flex items-center justify-center text-neutral-400 transition-colors hover:text-neutral-700 focus:outline-none",
      size: {
        sm: {
          height:                  "h-8",
          fontSize:                "text-sm",
          paddingLeft:             "pl-2.5",
          paddingRight:            "pr-2.5",
          withPrefix:              "pl-8",
          withSuffix:              "pr-8",
          adornmentWidth:          "w-8",
          floatingLabelX:          "10px",
          floatingLabelXWithPrefix: "32px",
        },
        md: {
          height:                  "h-10",
          fontSize:                "text-sm",
          paddingLeft:             "pl-3",
          paddingRight:            "pr-3",
          withPrefix:              "pl-9",
          withSuffix:              "pr-9",
          adornmentWidth:          "w-9",
          floatingLabelX:          "12px",
          floatingLabelXWithPrefix: "36px",
        },
        lg: {
          height:                  "h-11",
          fontSize:                "text-base",
          paddingLeft:             "pl-3.5",
          paddingRight:            "pr-3.5",
          withPrefix:              "pl-10",
          withSuffix:              "pr-10",
          adornmentWidth:          "w-10",
          floatingLabelX:          "14px",
          floatingLabelXWithPrefix: "40px",
        },
      },
      underline: {
        color:        "#94a3b8",
        invalidColor: "#f87171",
        height:       "1px",
        duration:     200,
      },
      floatingLabel: {
        color:              "#9ca3af",
        activeColor:        "#f97316",
        background:         "#ffffff",
        backgroundPaddingX: "3px",
        scale:              0.78,
        duration:           150,
      },
      glow: {
        type:     "static",
        color:    "rgba(249, 115, 22, 0.35)",
        blur:     10,
        spread:   4,
        radius:   10,
        opacity:  1,
        duration: 250,
      },
      gradientBorder: {
        stops:        ["#f97316", "#ec4899", "#8b5cf6"],
        invalidStops: ["#ef4444", "#f97316", "#ef4444"],
        width:        2,
        radius:       6,
        duration:     4,
        opacity:      0.9,
        fadeIn:       200,
      },
      svgStroke: {
        color:         "#f97316",
        invalidColor:  "#ef4444",
        width:         1.5,
        rx:            6,
        duration:      400,
        easing:        "ease-out",
        drawDirection: "clockwise",
      },
      inkDraw: {
        color:       "#f97316",
        invalidColor: "#ef4444",
        strokeWidth: 1.5,
        wobble:      2,
        rx:          6,
        duration:    350,
        easing:      "cubic-bezier(0.2, 0, 0, 1)",
      },
      corners: {
        style:    "corners",
        color:    "#f97316",
        invalidColor: "#ef4444",
        width:    2,
        length:   10,
        offset:   6,
        inset:    4,
        duration: 300,
        easing:   "ease-out",
      },
      characterReveal: {
        variant:    "char-fade",
        caretColor: "#374151",
        duration:   120,
        easing:     "ease-out",
      },
      cursorSpotlight: {
        color:   "rgba(249, 115, 22, 0.12)",
        radius:  80,
        fadeOut: 300,
      },
      bgReveal: {
        color:     "rgba(249, 115, 22, 0.07)",
        direction: "left",
        duration:  300,
        easing:    "ease-out",
      },
      ripple: {
        variant:  "ripple",
        color:    "rgba(249, 115, 22, 0.20)",
        duration: 600,
        radius:   6,
      },
      morphRadius: {
        rest:     "6px",
        focus:    "14px",
        duration: 250,
        easing:   "ease-out",
      },
      chromaBorder: {
        variant: "hue-rotate",
        opacity: 0.9,
        width:   2,
        radius:  6,
      },
    },

    textArea: {
      root:              "group flex flex-col gap-1.5",
      label:             "text-sm font-medium text-neutral-700 group-data-[disabled]:opacity-50",
      requiredIndicator: "ml-0.5 text-red-500",
      description:       "text-xs text-neutral-500",
      error:             "text-xs text-red-600",
      wrapper: [
        "relative flex overflow-hidden rounded-md border border-neutral-300 bg-white",
        "transition-[border-color,box-shadow]",
        "group-data-[focused]:border-orange-500 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-500/20",
        "group-data-[invalid]:border-red-500",
        "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
        "group-data-[disabled]:bg-neutral-50 group-data-[disabled]:cursor-not-allowed",
      ].join(" "),
      textarea: [
        "w-full bg-transparent text-neutral-900 placeholder:text-neutral-400",
        "focus:outline-none",
        "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:opacity-50",
        "group-data-[readonly]:text-neutral-600",
      ].join(" "),
      charCount:        "text-xs text-neutral-400 tabular-nums",
      charCountWarning: "text-xs text-amber-500 font-medium tabular-nums",
      charCountError:   "text-xs text-red-500 font-medium tabular-nums",
      size: {
        sm: { fontSize: "text-sm",   lineHeight: "1.25rem", padding: "px-3 py-2",   paddingYPx: 16, rows: 3 },
        md: { fontSize: "text-sm",   lineHeight: "1.25rem", padding: "px-3 py-2.5", paddingYPx: 20, rows: 3 },
        lg: { fontSize: "text-base", lineHeight: "1.5rem",  padding: "px-4 py-3",   paddingYPx: 24, rows: 4 },
      },
      glow: {
        type:    "static",
        color:   "rgba(249, 115, 22, 0.35)",
        blur:    8,
        spread:  5,
        radius:  10,
        opacity: 1,
      },
      gradientBorder: {
        stops:   ["#f97316", "#ec4899", "#a855f7", "#3b82f6"],
        width:   2,
        radius:  6,
        opacity: 0.9,
      },
      svgStroke: {
        color:        "#f97316",
        invalidColor: "#ef4444",
        width:        1.5,
        rx:           6,
        duration:     600,
        easing:       "ease-in-out",
      },
      morphRadius: {
        rest:     "0.375rem", // matches rounded-md on the wrapper
        focus:    "0.75rem",
        duration: 250,
        easing:   "ease-out",
      },
      chromaBorder: {
        variant: "hue-rotate",
        opacity: 0.9,
        width:   2,
        radius:  6,
      },
      bgReveal: {
        color:     "rgba(249, 115, 22, 0.07)",
        direction: "left",
        duration:  300,
        easing:    "ease-out",
      },
      ripple: {
        variant:  "pulse-rings",
        color:    "rgba(249, 115, 22, 0.35)",
        duration: 1500,
        radius:   6,
      },
      cursorSpotlight: {
        color:   "rgba(249, 115, 22, 0.10)",
        radius:  120,
        fadeOut: 300,
      },
      corners: {
        style:       "corners",
        color:       "#f97316",
        invalidColor: "#ef4444",
        width:       2,
        length:      10,
        offset:      6,
        inset:       4,
        duration:    300,
        easing:      "ease-out",
      },
      characterReveal: {
        variant:    "char-fade",
        caretColor: "#374151",
        duration:   120,
        easing:     "ease-out",
      },
      inkDraw: {
        color:        "#f97316",
        invalidColor: "#ef4444",
        strokeWidth:  1.5,
        wobble:       2,
        rx:           6,
        duration:     350,
        easing:       "cubic-bezier(0.2, 0, 0, 1)",
      },
    },

    tooltip: {
      container: "rounded-md bg-neutral-900 px-2.5 py-1.5 text-xs font-medium text-white shadow-lg",
      arrow:     "fill-neutral-900",
      offset:    8,
    },

    glowBorderButton: {
      colors: {
        stops: ["#f97316", "#ec4899", "#8b5cf6"],
      },
      border: {
        width:    2,
        radius:   12,
        duration: 5,
        opacity:  0.9,
      },
      glow: {
        blur:     20,
        opacity:  0.2,
        duration: 7.5,
        inset:    4,
      },
      surface: {
        // Deep mauve — dark but carries the warm orange-pink hue of the default palette
        bg:               "rgba(22, 5, 14, 0.96)",
        backdropBlur:     24,
        washOpacity:      0.12,
        highlightOpacity: 0.14,
        washDuration:     6,
      },
      content: {
        padding:       "14px 28px",
        fontSize:      15,
        fontWeight:    500,
        letterSpacing: "0.02em",
        color:         "#ffffff",
        fontFamily:    "Inter, -apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif",
        gap:           8,
      },
      focus: {
        color:  "rgba(249, 115, 22, 0.8)",
        width:  2,
        offset: 3,
      },
    },

    table: {
      container: {
        base:         "w-full overflow-auto relative border border-neutral-200 rounded-lg",
        maxHeight:    "max-h-[400px]",
        paddingRight: "pr-6",
      },
      header: {
        base: "bg-white sticky top-0 z-10 border-b-2 border-neutral-200",
        cell: {
          base:     "text-left text-sm font-semibold text-neutral-700 whitespace-nowrap select-none",
          sortable: "cursor-pointer hover:bg-neutral-50",
          sorted:   "text-neutral-900",
          padding:  "px-4 py-3",
        },
        sortIcon: {
          unsorted:   "opacity-40 text-sm",
          ascending:  "text-orange-700",
          descending: "text-orange-700",
        },
        resizer: {
          base:     "absolute right-0 top-0 h-full w-4 cursor-col-resize z-20 touch-none flex items-center justify-center",
          handle:   "w-0.5 h-1/2 rounded-full bg-neutral-300 transition-all duration-200",
          hover:    "bg-orange-600 h-full",
          dragging: "bg-orange-700 h-full",
          focused:  "bg-orange-600 h-full outline-2 outline-orange-600 -outline-offset-2",
        },
      },
      row: {
        base:     "border-b border-neutral-100 transition-colors",
        hover:    "hover:bg-neutral-50",
        selected: "bg-orange-50 hover:bg-orange-100",
        striped:  "even:bg-neutral-50/60",
        expanded: "bg-neutral-50",
        disabled: "opacity-50 pointer-events-none",
      },
      cell: {
        base:      "text-sm text-neutral-800",
        focusRing: "inset 0 0 0 2px #c2410c",
        focusBg:   "bg-orange-50",
        types: {
          text:     "whitespace-nowrap overflow-hidden text-ellipsis",
          numeric:  "text-right font-mono tabular-nums text-neutral-900",
          date:     "text-neutral-600 tabular-nums whitespace-nowrap",
          code:     "font-mono text-xs bg-neutral-100 rounded px-1",
          action:   "text-right whitespace-nowrap pr-2",
          checkbox: "w-10 px-3",
        },
      },
      density: {
        compact:     { paddingX: "px-3", paddingY: "py-1.5", fontSize: "text-xs", rowHeight: "h-8"  },
        default:     { paddingX: "px-4", paddingY: "py-3",   fontSize: "text-sm", rowHeight: "h-12" },
        comfortable: { paddingX: "px-5", paddingY: "py-4",   fontSize: "text-sm", rowHeight: "h-16" },
      },
      emptyState: "py-16 text-center text-sm text-neutral-500",
      skeleton: {
        row:  "animate-pulse",
        cell: "h-4 rounded bg-neutral-200",
      },
      pagination: {
        container: "flex items-center justify-between px-4 py-3 border-t border-neutral-200",
        info:      "text-sm text-neutral-600",
        controls:  "flex items-center gap-1",
      },
    },
  },
};

// ---------------------------------------------------------------------------
// Dark mode Checkbox config
// ---------------------------------------------------------------------------

export const darkCheckboxConfig: CheckboxConfig = {
  root: "group inline-flex items-center cursor-pointer data-[disabled]:cursor-not-allowed data-[disabled]:opacity-40",
  box: "shrink-0 flex items-center justify-center rounded border transition-colors",
  boxUnchecked: "border-white/20 bg-white/5",
  boxChecked: "border-orange-400 bg-orange-500",
  boxIndeterminate: "border-orange-400 bg-orange-500",
  boxDisabled: "",
  boxInvalid: "border-red-400",
  boxFocusVisible: "outline-none ring-2 ring-orange-400/40 ring-offset-1 ring-offset-transparent",
  icon: "text-white",
  label: "text-neutral-200 select-none",
  description: "text-neutral-400",
  size: {
    sm: { box: "h-3.5 w-3.5", fontSize: "text-xs",   gap: "gap-1.5", iconSize: "h-2.5 w-2.5" },
    md: { box: "h-4 w-4",     fontSize: "text-sm",   gap: "gap-2",   iconSize: "h-3 w-3" },
    lg: { box: "h-5 w-5",     fontSize: "text-base", gap: "gap-2.5", iconSize: "h-3.5 w-3.5" },
  },
};

export const darkCheckboxGroupConfig: CheckboxGroupConfig = {
  root:              "flex flex-col gap-1.5",
  label:             "text-sm font-medium text-neutral-200",
  requiredIndicator: "ml-0.5 text-red-400",
  description:       "text-xs text-neutral-400",
  error:             "text-xs text-red-400",
  items:             "flex flex-col gap-2",
};

// ---------------------------------------------------------------------------
// Dark mode RadioGroup config
// ---------------------------------------------------------------------------

export const darkRadioConfig: RadioConfig = {
  root: "group inline-flex items-center cursor-pointer data-[disabled]:cursor-not-allowed data-[disabled]:opacity-40",
  indicator: "shrink-0 flex items-center justify-center rounded-full border transition-colors",
  indicatorUnselected: "border-white/20 bg-white/5",
  indicatorSelected: "border-orange-400 bg-orange-500",
  indicatorDisabled: "",
  indicatorInvalid: "border-red-400",
  indicatorFocusVisible: "outline-none ring-2 ring-orange-400/40 ring-offset-1 ring-offset-transparent",
  dot: "rounded-full bg-white",
  label: "text-neutral-200 select-none",
  description: "text-neutral-400",
  size: {
    sm: { indicator: "h-3.5 w-3.5", dot: "h-1.5 w-1.5", fontSize: "text-xs",   gap: "gap-1.5" },
    md: { indicator: "h-4 w-4",     dot: "h-2 w-2",     fontSize: "text-sm",   gap: "gap-2"   },
    lg: { indicator: "h-5 w-5",     dot: "h-2.5 w-2.5", fontSize: "text-base", gap: "gap-2.5" },
  },
};

export const darkRadioGroupConfig: RadioGroupConfig = {
  root:              "flex flex-col gap-1.5",
  label:             "text-sm font-medium text-neutral-200",
  requiredIndicator: "ml-0.5 text-red-400",
  description:       "text-xs text-neutral-400",
  error:             "text-xs text-red-400",
  items:             "flex flex-col gap-2",
  itemsHorizontal:   "flex flex-row flex-wrap gap-x-4 gap-y-2",
};

// ---------------------------------------------------------------------------
// Dark mode Switch config
// ---------------------------------------------------------------------------

export const darkDrawerConfig: DrawerConfig = {
  overlay:    "fixed inset-0 z-50 bg-black/60",
  panel:      "z-50 bg-neutral-900 shadow-2xl outline-none flex flex-col border-white/10",
  horizontal: {
    sm:   "w-64",
    md:   "w-80",
    lg:   "w-96",
    full: "w-screen",
  },
  vertical: {
    sm:   "h-48",
    md:   "h-64",
    lg:   "h-96",
    full: "h-dvh",
  },
  header:      "flex items-center justify-between px-6 py-4 border-b border-white/10 shrink-0",
  title:       "text-base font-semibold text-neutral-100",
  closeButton: "rounded-md p-1 text-neutral-500 hover:text-neutral-300 hover:bg-white/10 transition-colors outline-none focus-visible:ring-2 focus-visible:ring-orange-400/40",
  body:        "flex-1 overflow-y-auto px-6 py-4 min-h-0",
  footer:      "flex items-center justify-end gap-3 px-6 py-4 border-t border-white/10 shrink-0",
};

export const darkDialogConfig: DialogConfig = {
  overlay: "fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4",
  panel: "bg-neutral-900 shadow-2xl outline-none flex flex-col w-full border border-white/10",
  size: {
    sm:   "max-w-sm   max-h-[85vh] rounded-xl",
    md:   "max-w-lg   max-h-[85vh] rounded-xl",
    lg:   "max-w-2xl  max-h-[90vh] rounded-xl",
    full: "max-w-none max-h-none   rounded-none w-screen h-dvh",
  },
  header:      "flex items-center justify-between px-6 py-4 border-b border-white/10 shrink-0",
  title:       "text-base font-semibold text-neutral-100",
  closeButton: "rounded-md p-1 text-neutral-500 hover:text-neutral-300 hover:bg-white/10 transition-colors outline-none focus-visible:ring-2 focus-visible:ring-orange-400/40",
  body:        "flex-1 overflow-y-auto px-6 py-4 min-h-0",
  footer:      "flex items-center justify-end gap-3 px-6 py-4 border-t border-white/10 shrink-0",
};

export const darkPopoverConfig: PopoverConfig = {
  container: "rounded-lg border border-white/10 bg-neutral-900 shadow-xl outline-none",
  arrow: "fill-neutral-900 stroke-white/10",
  offset: 8,
};

export const darkSliderConfig: SliderConfig = {
  root: "flex flex-col gap-2 w-full",
  label: "text-sm font-medium text-neutral-200",
  output: "text-sm tabular-nums text-neutral-400",
  track: "relative w-full rounded-full cursor-pointer",
  trackUnfilled: "bg-white/15",
  trackFilled: "rounded-full bg-orange-500",
  thumb: "absolute top-1/2 -translate-y-1/2 rounded-full bg-white border-2 border-orange-400 shadow transition-colors cursor-grab active:cursor-grabbing",
  thumbFocusVisible: "outline-none ring-2 ring-orange-400/40 ring-offset-1 ring-offset-transparent",
  thumbDragging: "cursor-grabbing",
  description: "text-xs text-neutral-400",
  error: "text-xs text-red-400",
  size: {
    sm: { trackHeight: "h-1",   thumb: "h-3.5 w-3.5", fontSize: "text-xs" },
    md: { trackHeight: "h-1.5", thumb: "h-4 w-4",     fontSize: "text-sm" },
  },
};

export const darkSwitchConfig: SwitchConfig = {
  root: "group inline-flex items-center cursor-pointer data-[disabled]:cursor-not-allowed data-[disabled]:opacity-40",
  track: "shrink-0 inline-flex items-center rounded-full p-0.5 transition-colors",
  trackOff: "bg-white/20",
  trackOn: "bg-orange-500",
  trackDisabled: "",
  trackFocusVisible: "outline-none ring-2 ring-orange-400/40 ring-offset-1 ring-offset-transparent",
  thumb: "rounded-full bg-white shadow transition-transform",
  label: "text-neutral-200 select-none",
  size: {
    sm: { track: "w-7 h-4",  thumb: "h-3 w-3", thumbTranslate: "translateX(12px)", fontSize: "text-xs",  gap: "gap-1.5" },
    md: { track: "w-9 h-5",  thumb: "h-4 w-4", thumbTranslate: "translateX(16px)", fontSize: "text-sm",  gap: "gap-2"   },
  },
};

// ---------------------------------------------------------------------------
// Dark mode TextField config
//
// Drop-in replacement for defaultTheme.components.textField when the
// surrounding page has a dark background. Uses white/opacity values so it
// works on any dark surface without hard-coding a specific background color.
// ---------------------------------------------------------------------------

export const darkTextFieldConfig: TextFieldConfig = {
  root:              "group flex flex-col gap-1.5",
  label:             "text-sm font-medium text-neutral-200 group-data-[disabled]:opacity-40",
  requiredIndicator: "ml-0.5 text-red-400",
  description:       "text-xs text-neutral-400",
  error:             "text-xs text-red-400",
  inputWrapper: [
    "relative flex items-center overflow-hidden rounded-md border border-white/10 bg-white/5",
    "transition-[border-color,box-shadow]",
    "group-data-[focused]:border-orange-400 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-400/20",
    "group-data-[invalid]:border-red-500",
    "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
    "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:bg-white/[0.02] group-data-[disabled]:opacity-40",
  ].join(" "),
  input:       "flex-1 h-full bg-transparent text-neutral-100 outline-none placeholder:text-white/30 group-data-[disabled]:cursor-not-allowed",
  adornment:   "absolute flex items-center justify-center text-white/30 pointer-events-none select-none",
  clearButton: "absolute flex items-center justify-center text-white/30 transition-colors hover:text-white/60 focus:outline-none",
  size: {
    sm: {
      height:                  "h-8",
      fontSize:                "text-sm",
      paddingLeft:             "pl-2.5",
      paddingRight:            "pr-2.5",
      withPrefix:              "pl-8",
      withSuffix:              "pr-8",
      adornmentWidth:          "w-8",
      floatingLabelX:          "10px",
      floatingLabelXWithPrefix: "32px",
    },
    md: {
      height:                  "h-10",
      fontSize:                "text-sm",
      paddingLeft:             "pl-3",
      paddingRight:            "pr-3",
      withPrefix:              "pl-9",
      withSuffix:              "pr-9",
      adornmentWidth:          "w-9",
      floatingLabelX:          "12px",
      floatingLabelXWithPrefix: "36px",
    },
    lg: {
      height:                  "h-11",
      fontSize:                "text-base",
      paddingLeft:             "pl-3.5",
      paddingRight:            "pr-3.5",
      withPrefix:              "pl-10",
      withSuffix:              "pr-10",
      adornmentWidth:          "w-10",
      floatingLabelX:          "14px",
      floatingLabelXWithPrefix: "40px",
    },
  },
  underline: {
    color:        "rgba(148, 163, 184, 0.45)",
    invalidColor: "#fca5a5",
    height:       "1px",
    duration:     200,
  },
  floatingLabel: {
    color:              "rgba(255, 255, 255, 0.35)",
    activeColor:        "#fb923c",
    // Set to your page's dark background colour so the label punches
    // through the input border when floating. Default: NeverChess dark bg.
    background:         "#0f1923",
    backgroundPaddingX: "3px",
    scale:              0.78,
    duration:           150,
  },
  glow: {
    type:           "static",
    color:          "rgba(251, 146, 60, 0.25)",
    blur:           8,
    spread:         3,
    radius:         9,
    opacity:        0.8,
    duration:       250,
    maskBackground: "#0f1923",
  },
  gradientBorder: {
    stops:        ["#fb923c", "#f472b6", "#a78bfa"],
    invalidStops: ["#f87171", "#fb923c", "#f87171"],
    width:        2,
    radius:       6,
    duration:     4,
    opacity:      0.85,
    fadeIn:       200,
  },
  svgStroke: {
    color:         "#fb923c",
    invalidColor:  "#f87171",
    width:         1.5,
    rx:            6,
    duration:      400,
    easing:        "ease-out",
    drawDirection: "clockwise",
  },
  inkDraw: {
    color:       "#fb923c",
    invalidColor: "#f87171",
    strokeWidth: 1.5,
    wobble:      2,
    rx:          6,
    duration:    350,
    easing:      "cubic-bezier(0.2, 0, 0, 1)",
  },
  corners: {
    style:       "corners",
    color:       "#fb923c",
    invalidColor: "#f87171",
    width:       2,
    length:      10,
    offset:      6,
    inset:       4,
    duration:    300,
    easing:      "ease-out",
  },
  characterReveal: {
    variant:    "char-fade",
    caretColor: "rgba(255, 255, 255, 0.9)",
    duration:   120,
    easing:     "ease-out",
  },
  cursorSpotlight: {
    color:   "rgba(251, 146, 60, 0.14)",
    radius:  80,
    fadeOut: 300,
  },
  bgReveal: {
    color:     "rgba(251, 146, 60, 0.08)",
    direction: "left",
    duration:  300,
    easing:    "ease-out",
  },
  ripple: {
    variant:  "ripple",
    color:    "rgba(251, 146, 60, 0.22)",
    duration: 600,
    radius:   6,
  },
  morphRadius: {
    rest:     "6px",
    focus:    "14px",
    duration: 250,
    easing:   "ease-out",
  },
  chromaBorder: {
    variant: "hue-rotate",
    opacity: 0.9,
    width:   2,
    radius:  6,
  },
};

// ---------------------------------------------------------------------------
// TextArea standalone dark config
// ---------------------------------------------------------------------------

export const darkTextAreaConfig: TextAreaConfig = {
  root:              "group flex flex-col gap-1.5",
  label:             "text-sm font-medium text-neutral-200 group-data-[disabled]:opacity-40",
  requiredIndicator: "ml-0.5 text-red-400",
  description:       "text-xs text-neutral-400",
  error:             "text-xs text-red-400",
  wrapper: [
    "relative flex overflow-hidden rounded-md border border-white/10 bg-white/5",
    "transition-[border-color,box-shadow]",
    "group-data-[focused]:border-orange-400 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-400/20",
    "group-data-[invalid]:border-red-500",
    "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
    "group-data-[disabled]:bg-white/[0.02] group-data-[disabled]:cursor-not-allowed",
  ].join(" "),
  textarea: [
    "w-full bg-transparent text-neutral-100 placeholder:text-neutral-500",
    "focus:outline-none",
    "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:opacity-40",
    "group-data-[readonly]:text-neutral-400",
  ].join(" "),
  charCount:        "text-xs text-neutral-500 tabular-nums",
  charCountWarning: "text-xs text-amber-400 font-medium tabular-nums",
  charCountError:   "text-xs text-red-400 font-medium tabular-nums",
  size: {
    sm: { fontSize: "text-sm",   lineHeight: "1.25rem", padding: "px-3 py-2",   paddingYPx: 16, rows: 3 },
    md: { fontSize: "text-sm",   lineHeight: "1.25rem", padding: "px-3 py-2.5", paddingYPx: 20, rows: 3 },
    lg: { fontSize: "text-base", lineHeight: "1.5rem",  padding: "px-4 py-3",   paddingYPx: 24, rows: 4 },
  },
  glow: {
    type:           "static",
    color:          "rgba(249, 115, 22, 0.45)",
    blur:           8,
    spread:         5,
    radius:         10,
    opacity:        1,
    maskBackground: "#0f1923",
  },
  gradientBorder: {
    stops:   ["#f97316", "#ec4899", "#a855f7", "#3b82f6"],
    width:   2,
    radius:  6,
    opacity: 0.9,
  },
  svgStroke: {
    color:        "#f97316",
    invalidColor: "#ef4444",
    width:        1.5,
    rx:           6,
    duration:     600,
    easing:       "ease-in-out",
  },
  morphRadius: {
    rest:     "0.375rem",
    focus:    "0.75rem",
    duration: 250,
    easing:   "ease-out",
  },
  chromaBorder: {
    variant: "hue-rotate",
    opacity: 0.9,
    width:   2,
    radius:  6,
  },
  bgReveal: {
    color:     "rgba(251, 146, 60, 0.08)",
    direction: "left",
    duration:  300,
    easing:    "ease-out",
  },
  ripple: {
    variant:  "pulse-rings",
    color:    "rgba(251, 146, 60, 0.40)",
    duration: 1500,
    radius:   6,
  },
  cursorSpotlight: {
    color:   "rgba(251, 146, 60, 0.12)",
    radius:  120,
    fadeOut: 300,
  },
  corners: {
    style:        "corners",
    color:        "#fb923c",
    invalidColor: "#f87171",
    width:        2,
    length:       10,
    offset:       6,
    inset:        4,
    duration:     300,
    easing:       "ease-out",
  },
  characterReveal: {
    variant:    "char-fade",
    caretColor: "rgba(255, 255, 255, 0.9)",
    duration:   120,
    easing:     "ease-out",
  },
  inkDraw: {
    color:        "#fb923c",
    invalidColor: "#f87171",
    strokeWidth:  1.5,
    wobble:       2,
    rx:           6,
    duration:     350,
    easing:       "cubic-bezier(0.2, 0, 0, 1)",
  },
};

// ---------------------------------------------------------------------------
// NumberField standalone dark config
// ---------------------------------------------------------------------------

export const darkComboBoxConfig: ComboBoxConfig = {
  root:              "group flex flex-col gap-1.5",
  label:             "text-sm font-medium text-neutral-200 group-data-[disabled]:opacity-40",
  requiredIndicator: "ml-0.5 text-red-400",
  description:       "text-xs text-neutral-400",
  error:             "text-xs text-red-400",
  inputWrapper: [
    "relative flex items-center overflow-hidden rounded-md border border-white/10 bg-white/5",
    "transition-[border-color,box-shadow]",
    "group-data-[focused]:border-orange-400 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-400/20",
    "group-data-[open]:border-orange-400 group-data-[open]:ring-2 group-data-[open]:ring-orange-400/20",
    "group-data-[invalid]:border-red-500",
    "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
    "group-data-[invalid]:group-data-[open]:ring-red-500/20",
    "group-data-[disabled]:bg-white/[0.02] group-data-[disabled]:cursor-not-allowed group-data-[disabled]:opacity-40",
  ].join(" "),
  input:    "flex-1 h-full bg-transparent text-neutral-100 outline-none placeholder:text-neutral-500 group-data-[disabled]:cursor-not-allowed",
  button: [
    "shrink-0 flex items-center justify-center text-neutral-500",
    "outline-none data-[focus-visible]:outline-none",
    "hover:text-neutral-300",
    "transition-transform duration-200 group-data-[open]:rotate-180",
  ].join(" "),
  adornment:     "absolute flex items-center justify-center text-neutral-500 pointer-events-none select-none",
  popover: [
    "min-w-[var(--trigger-width)] rounded-md border border-white/10 bg-neutral-900 shadow-xl outline-none z-50",
    "mr-sf-popover",
  ].join(" "),
  listBox:       "p-1 max-h-64 overflow-y-auto overflow-x-hidden outline-none",
  item:          "flex items-center gap-2 px-2 py-1.5 rounded-sm text-sm text-neutral-200 cursor-default outline-none select-none transition-colors",
  itemFocused:   "bg-orange-400/10 text-orange-300",
  itemSelected:  "font-medium",
  itemDisabled:  "opacity-40 cursor-not-allowed",
  sectionHeader: "px-2 py-1 mt-1 text-xs font-semibold text-neutral-500 uppercase tracking-wide select-none",
  separator:     "my-1 border-t border-white/10",
  size: {
    sm: { height: "h-8",  fontSize: "text-sm",   paddingLeft: "pl-2.5", withPrefix: "pl-8",  paddingRight: "pr-8",  adornmentWidth: "w-8",  buttonWidth: "w-8"  },
    md: { height: "h-10", fontSize: "text-sm",   paddingLeft: "pl-3",   withPrefix: "pl-9",  paddingRight: "pr-9",  adornmentWidth: "w-9",  buttonWidth: "w-9"  },
    lg: { height: "h-11", fontSize: "text-base", paddingLeft: "pl-3.5", withPrefix: "pl-10", paddingRight: "pr-10", adornmentWidth: "w-10", buttonWidth: "w-10" },
  },
  glow: {
    type:           "static",
    color:          "rgba(249, 115, 22, 0.45)",
    blur:           10,
    spread:         4,
    radius:         10,
    opacity:        1,
    maskBackground: "#0f1923",
  },
  gradientBorder: {
    stops:   ["#f97316", "#ec4899", "#a855f7", "#3b82f6"],
    width:   2,
    radius:  6,
    opacity: 0.9,
  },
  svgStroke: {
    color:        "#f97316",
    invalidColor: "#ef4444",
    width:        1.5,
    rx:           6,
    duration:     400,
    easing:       "ease-out",
  },
  corners: {
    style:        "corners",
    color:        "#fb923c",
    invalidColor: "#f87171",
    width:        2,
    length:       10,
    offset:       6,
    inset:        4,
    duration:     300,
    easing:       "ease-out",
  },
  bgReveal: {
    color:     "rgba(251, 146, 60, 0.08)",
    direction: "left",
    duration:  300,
    easing:    "ease-out",
  },
  ripple: {
    variant:  "pulse-rings",
    color:    "rgba(251, 146, 60, 0.40)",
    duration: 1500,
    radius:   6,
  },
  cursorSpotlight: {
    color:   "rgba(251, 146, 60, 0.12)",
    radius:  80,
    fadeOut: 300,
  },
  inkDraw: {
    color:        "#fb923c",
    invalidColor: "#f87171",
    strokeWidth:  1.5,
    wobble:       2,
    rx:           6,
    duration:     350,
    easing:       "cubic-bezier(0.2, 0, 0, 1)",
  },
  morphRadius: {
    rest:     "0.375rem",
    focus:    "0.75rem",
    duration: 250,
    easing:   "ease-out",
  },
  chromaBorder: {
    variant: "hue-rotate",
    opacity: 0.9,
    width:   2,
    radius:  6,
  },
};

export const darkSelectFieldConfig: SelectFieldConfig = {
  root:              "group flex flex-col gap-1.5",
  label:             "text-sm font-medium text-neutral-200 group-data-[disabled]:opacity-40",
  requiredIndicator: "ml-0.5 text-red-400",
  description:       "text-xs text-neutral-400",
  error:             "text-xs text-red-400",
  trigger: [
    "relative flex items-center w-full overflow-hidden rounded-md border border-white/10 bg-white/5 cursor-pointer",
    "outline-none data-[focus-visible]:outline-none",
    "transition-[border-color,box-shadow]",
    "group-data-[focused]:border-orange-400 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-400/20",
    "group-data-[open]:border-orange-400 group-data-[open]:ring-2 group-data-[open]:ring-orange-400/20",
    "group-data-[invalid]:border-red-500",
    "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
    "group-data-[invalid]:group-data-[open]:ring-red-500/20",
    "group-data-[disabled]:bg-white/[0.02] group-data-[disabled]:cursor-not-allowed group-data-[disabled]:opacity-40",
  ].join(" "),
  valueText:   "text-neutral-100",
  placeholder: "text-neutral-500",
  chevron: [
    "shrink-0 flex items-center justify-center text-neutral-500 pointer-events-none",
    "transition-transform duration-200 group-data-[open]:rotate-180",
  ].join(" "),
  popover: [
    "min-w-[var(--trigger-width)] rounded-md border border-white/10 bg-neutral-900 shadow-xl outline-none z-50",
    "mr-sf-popover",
  ].join(" "),
  listBox:       "p-1 max-h-64 overflow-y-auto overflow-x-hidden outline-none",
  item:          "flex items-center gap-2 px-2 py-1.5 rounded-sm text-sm text-neutral-200 cursor-default outline-none select-none transition-colors",
  itemFocused:   "bg-orange-400/10 text-orange-300",
  itemSelected:  "font-medium",
  itemDisabled:  "opacity-40 cursor-not-allowed",
  sectionHeader: "px-2 py-1 mt-1 text-xs font-semibold text-neutral-500 uppercase tracking-wide select-none",
  separator:     "my-1 border-t border-white/10",
  size: {
    sm: { height: "h-8",  fontSize: "text-sm",   paddingLeft: "pl-2.5", chevronWidth: "w-8"  },
    md: { height: "h-10", fontSize: "text-sm",   paddingLeft: "pl-3",   chevronWidth: "w-9"  },
    lg: { height: "h-11", fontSize: "text-base", paddingLeft: "pl-3.5", chevronWidth: "w-10" },
  },
  glow: {
    type:           "static",
    color:          "rgba(249, 115, 22, 0.45)",
    blur:           10,
    spread:         4,
    radius:         10,
    opacity:        1,
    maskBackground: "#0f1923",
  },
  gradientBorder: {
    stops:   ["#f97316", "#ec4899", "#a855f7", "#3b82f6"],
    width:   2,
    radius:  6,
    opacity: 0.9,
  },
  svgStroke: {
    color:        "#f97316",
    invalidColor: "#ef4444",
    width:        1.5,
    rx:           6,
    duration:     400,
    easing:       "ease-out",
  },
  corners: {
    style:        "corners",
    color:        "#fb923c",
    invalidColor: "#f87171",
    width:        2,
    length:       10,
    offset:       6,
    inset:        4,
    duration:     300,
    easing:       "ease-out",
  },
  bgReveal: {
    color:     "rgba(251, 146, 60, 0.08)",
    direction: "left",
    duration:  300,
    easing:    "ease-out",
  },
  ripple: {
    variant:  "pulse-rings",
    color:    "rgba(251, 146, 60, 0.40)",
    duration: 1500,
    radius:   6,
  },
  cursorSpotlight: {
    color:   "rgba(251, 146, 60, 0.12)",
    radius:  80,
    fadeOut: 300,
  },
  inkDraw: {
    color:        "#fb923c",
    invalidColor: "#f87171",
    strokeWidth:  1.5,
    wobble:       2,
    rx:           6,
    duration:     350,
    easing:       "cubic-bezier(0.2, 0, 0, 1)",
  },
  morphRadius: {
    rest:     "0.375rem",
    focus:    "0.75rem",
    duration: 250,
    easing:   "ease-out",
  },
  chromaBorder: {
    variant: "hue-rotate",
    opacity: 0.9,
    width:   2,
    radius:  6,
  },
};

export const darkSearchFieldConfig: SearchFieldConfig = {
  root:              "group flex flex-col gap-1.5",
  label:             "text-sm font-medium text-neutral-200 group-data-[disabled]:opacity-40",
  requiredIndicator: "ml-0.5 text-red-400",
  description:       "text-xs text-neutral-400",
  error:             "text-xs text-red-400",
  inputWrapper: [
    "relative flex items-center overflow-hidden rounded-md border border-white/10 bg-white/5",
    "transition-[border-color,box-shadow]",
    "group-data-[focused]:border-orange-400 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-400/20",
    "group-data-[invalid]:border-red-500",
    "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
    "group-data-[disabled]:bg-white/[0.02] group-data-[disabled]:cursor-not-allowed group-data-[disabled]:opacity-40",
  ].join(" "),
  input:       "flex-1 h-full bg-transparent text-neutral-100 outline-none placeholder:text-neutral-500 group-data-[disabled]:cursor-not-allowed",
  adornment:   "absolute flex items-center justify-center text-neutral-500 pointer-events-none select-none",
  clearButton: "absolute flex items-center justify-center text-neutral-500 transition-colors hover:text-neutral-300 focus:outline-none",
  size: {
    sm: { height: "h-8",  fontSize: "text-sm",   paddingLeft: "pl-2.5", paddingRight: "pr-2.5", withPrefix: "pl-8",  withSuffix: "pr-8",  adornmentWidth: "w-8"  },
    md: { height: "h-10", fontSize: "text-sm",   paddingLeft: "pl-3",   paddingRight: "pr-3",   withPrefix: "pl-9",  withSuffix: "pr-9",  adornmentWidth: "w-9"  },
    lg: { height: "h-11", fontSize: "text-base", paddingLeft: "pl-3.5", paddingRight: "pr-3.5", withPrefix: "pl-10", withSuffix: "pr-10", adornmentWidth: "w-10" },
  },
  glow: {
    type:           "static",
    color:          "rgba(249, 115, 22, 0.45)",
    blur:           10,
    spread:         4,
    radius:         10,
    opacity:        1,
    maskBackground: "#0f1923",
  },
  gradientBorder: {
    stops:   ["#f97316", "#ec4899", "#a855f7", "#3b82f6"],
    width:   2,
    radius:  6,
    opacity: 0.9,
  },
  svgStroke: {
    color:        "#f97316",
    invalidColor: "#ef4444",
    width:        1.5,
    rx:           6,
    duration:     400,
    easing:       "ease-out",
  },
  corners: {
    style:        "corners",
    color:        "#fb923c",
    invalidColor: "#f87171",
    width:        2,
    length:       10,
    offset:       6,
    inset:        4,
    duration:     300,
    easing:       "ease-out",
  },
  bgReveal: {
    color:     "rgba(251, 146, 60, 0.08)",
    direction: "left",
    duration:  300,
    easing:    "ease-out",
  },
  ripple: {
    variant:  "pulse-rings",
    color:    "rgba(251, 146, 60, 0.40)",
    duration: 1500,
    radius:   6,
  },
  cursorSpotlight: {
    color:   "rgba(251, 146, 60, 0.12)",
    radius:  80,
    fadeOut: 300,
  },
  characterReveal: {
    variant:    "char-fade",
    caretColor: "rgba(255, 255, 255, 0.9)",
    duration:   120,
    easing:     "ease-out",
  },
  inkDraw: {
    color:        "#fb923c",
    invalidColor: "#f87171",
    strokeWidth:  1.5,
    wobble:       2,
    rx:           6,
    duration:     350,
    easing:       "cubic-bezier(0.2, 0, 0, 1)",
  },
  morphRadius: {
    rest:     "0.375rem",
    focus:    "0.75rem",
    duration: 250,
    easing:   "ease-out",
  },
  chromaBorder: {
    variant: "hue-rotate",
    opacity: 0.9,
    width:   2,
    radius:  6,
  },
};

export const darkNumberFieldConfig: NumberFieldConfig = {
  root:              "group flex flex-col gap-1.5",
  label:             "text-sm font-medium text-neutral-200 group-data-[disabled]:opacity-40",
  requiredIndicator: "ml-0.5 text-red-400",
  description:       "text-xs text-neutral-400",
  error:             "text-xs text-red-400",
  group: [
    "relative flex w-full overflow-hidden rounded-md border border-white/10 bg-white/5",
    "transition-[border-color,box-shadow]",
    "group-data-[focused]:border-orange-400 group-data-[focused]:ring-2 group-data-[focused]:ring-orange-400/20",
    "group-data-[invalid]:border-red-500",
    "group-data-[invalid]:group-data-[focused]:ring-red-500/20",
    "group-data-[disabled]:bg-white/[0.02] group-data-[disabled]:cursor-not-allowed",
  ].join(" "),
  input: [
    "flex-1 min-w-0 h-full bg-transparent text-neutral-100 placeholder:text-neutral-500 tabular-nums",
    "focus:outline-none",
    "group-data-[disabled]:cursor-not-allowed group-data-[disabled]:opacity-40",
  ].join(" "),
  stepperColumn:    "flex flex-col shrink-0 border-l border-white/10",
  stepperSeparator: "border-t border-white/10",
  stepperButton: [
    "flex flex-1 items-center justify-center text-neutral-500",
    "hover:bg-white/5 hover:text-neutral-300",
    "data-[pressed]:bg-white/10",
    "data-[disabled]:opacity-40 data-[disabled]:cursor-not-allowed data-[disabled]:hover:bg-transparent",
    "data-[focus-visible]:outline-none data-[focus-visible]:ring-2 data-[focus-visible]:ring-inset data-[focus-visible]:ring-orange-400/50",
    "transition-colors",
  ].join(" "),
  size: {
    sm: { height: "h-8",  fontSize: "text-sm",   paddingLeft: "pl-2.5", stepperWidth: "w-7" },
    md: { height: "h-9",  fontSize: "text-sm",   paddingLeft: "pl-3",   stepperWidth: "w-8" },
    lg: { height: "h-10", fontSize: "text-base", paddingLeft: "pl-3.5", stepperWidth: "w-9" },
  },
  glow: {
    type:           "static",
    color:          "rgba(249, 115, 22, 0.45)",
    blur:           8,
    spread:         5,
    radius:         10,
    opacity:        1,
    maskBackground: "#0f1923",
  },
  gradientBorder: {
    stops:   ["#f97316", "#ec4899", "#a855f7", "#3b82f6"],
    width:   2,
    radius:  6,
    opacity: 0.9,
  },
  svgStroke: {
    color:        "#f97316",
    invalidColor: "#ef4444",
    width:        1.5,
    rx:           6,
    duration:     400,
    easing:       "ease-out",
  },
  corners: {
    style:        "corners",
    color:        "#fb923c",
    invalidColor: "#f87171",
    width:        2,
    length:       10,
    offset:       6,
    inset:        4,
    duration:     300,
    easing:       "ease-out",
  },
  bgReveal: {
    color:     "rgba(251, 146, 60, 0.08)",
    direction: "left",
    duration:  300,
    easing:    "ease-out",
  },
  ripple: {
    variant:  "pulse-rings",
    color:    "rgba(251, 146, 60, 0.40)",
    duration: 1500,
    radius:   6,
  },
  cursorSpotlight: {
    color:   "rgba(251, 146, 60, 0.12)",
    radius:  80,
    fadeOut: 300,
  },
  inkDraw: {
    color:        "#fb923c",
    invalidColor: "#f87171",
    strokeWidth:  1.5,
    wobble:       2,
    rx:           6,
    duration:     350,
    easing:       "cubic-bezier(0.2, 0, 0, 1)",
  },
  morphRadius: {
    rest:     "0.375rem",
    focus:    "0.75rem",
    duration: 250,
    easing:   "ease-out",
  },
  chromaBorder: {
    variant: "hue-rotate",
    opacity: 0.9,
    width:   2,
    radius:  6,
  },
};
